# Generated by Django 4.1.5 on 2023-06-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penghijauan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(db_column='Kecamatan', max_length=100, verbose_name='kecamatan')),
                ('kode_kelurahan', models.CharField(db_column='Kode Kelurahan', max_length=100, verbose_name='kode kelurahan')),
                ('kelurahan', models.CharField(db_column='Kelurahan', max_length=100, verbose_name='kelurahan')),
                ('jenis_pohon', models.CharField(db_column='Jenis Pohon Yang Ditanam', max_length=100, verbose_name='jenis pohon')),
                ('lokasi_penanaman', models.CharField(db_column='Lokasi Penanaman (RW)', max_length=100, verbose_name='lokasi penanaman')),
                ('jumlah_pohon', models.IntegerField(db_column='Jumlah Pohon Ditanam')),
            ],
        ),
        migrations.CreateModel(
            name='Rth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(max_length=100)),
                ('kode_kelurahan', models.CharField(max_length=100)),
                ('kelurahan', models.CharField(max_length=100)),
                ('lokasi_rth', models.CharField(max_length=100)),
                ('jenis_rth', models.CharField(max_length=100)),
                ('luas_rth', models.IntegerField(db_column='luas_rth(m2)')),
            ],
        ),
        migrations.CreateModel(
            name='Taman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(db_column='Kecamatan', max_length=100, verbose_name='kecamatan')),
                ('kode_kelurahan', models.CharField(db_column='Kode Kelurahan', max_length=100, verbose_name='kode kelurahan')),
                ('kelurahan', models.CharField(db_column='Kelurahan', max_length=100, verbose_name='kelurahan')),
                ('nama_taman', models.CharField(db_column='Nama Taman', max_length=200, verbose_name='nama taman')),
                ('lokasi_taman', models.CharField(db_column='Lokasi Taman', max_length=200, verbose_name='lokasi taman')),
                ('luas_taman', models.IntegerField(db_column='Luas Taman (m2)')),
            ],
        ),
    ]
